# Generated by Django 5.2.12 on 2026-03-21 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('driver_code', models.TextField(unique=True)),
                ('depot_id', models.BigIntegerField()),
                ('max_minutes', models.IntegerField()),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('depot', models.TextField(blank=True, null=True)),
                ('client_name', models.TextField(blank=True, null=True)),
                ('service_time', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('floor', models.FloatField(blank=True, null=True)),
                ('order_id', models.TextField(blank=True, null=True)),
                ('weekly_1', models.BooleanField(blank=True, null=True)),
                ('weekly_2', models.BooleanField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_points',
                'managed': False,
            },
        ),
    ]
